### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by zilingdousheng** [JingzheSun/Recommender_System_Adaptive_KNN#1]
def prediction(self, u, i):
        scores = self.predictions(u) # This should be self.predictionsAll(u)
        return scores[i] > sorted(scores)[self._numItem*0.8]

**Comment by JingzheSun** [comment]
@zilingdousheng 
Thank you, fixed.

**Comment by zilingdousheng** [comment]
def predictionsKNN(self, K, u):
        #slow
        if K >= self._Iu[u]: #This should be len(self._Iu[u])
            res = np.sum([self.C[:,l] for l in self._Iu[u]], 0)
